CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  pass VARCHAR(40) NOT NULL,
  full_name VARCHAR(60) NOT NULL);
CREATE TABLE channels (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  url TEXT NOT NULL);
CREATE TABLE news (
  guid VARCHAR(255) PRIMARY KEY,
  title TEXT NOT NULL,
  link TEXT NOT NULL,
  description TEXT NOT NULL,
  pub_date TIMESTAMP,
  channel_id INTEGER REFERENCES channels ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE user_channel (
  user_id INTEGER REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  channel_id INTEGER REFERENCES channels ON UPDATE CASCADE ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  UNIQUE(user_id, channel_id));
CREATE TABLE user_news (
  user_id INTEGER REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  news_id VARCHAR(255) REFERENCES news ON UPDATE CASCADE ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL,
  UNIQUE(user_id, news_id));
