DROP TABLE users IF EXISTS;
DROP TABLE channels IF EXISTS;
DROP TABLE news IF EXISTS;
DROP TABLE user_channel IF EXISTS;
DROP TABLE user_news IF EXISTS;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  pass CHAR(40) NOT NULL,
  salt CHAR(32) NOT NULL,
  full_name VARCHAR(60) NOT NULL);
CREATE TABLE channels (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  url VARCHAR NOT NULL);
CREATE TABLE news (
  guid VARCHAR PRIMARY KEY,
  title VARCHAR NOT NULL,
  link VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  pub_date TIMESTAMP,
  channel_id INTEGER REFERENCES channels ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE user_channel (
  user_id INTEGER REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  channel_id INTEGER REFERENCES channels ON UPDATE CASCADE ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  UNIQUE(user_id, channel_id));
CREATE TABLE user_news (
  user_id INTEGER REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
  news_id VARCHAR REFERENCES news ON UPDATE CASCADE ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL,
  UNIQUE(user_id, news_id));
